# Generated by Django 4.1.13 on 2024-04-28 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_about_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
